apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homework-http-gateway
  namespace: homework
spec:
  gatewayClassName: traefik
  listeners:
    - name: http-listener
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: All
