apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homework-http-gateway
  namespace: homework
  annotations:
    traefik.io/gateway.entrypoints: web
spec:
  gatewayClassName: traefik
  listeners:
  - name: http-listener
    protocol: HTTP
    port: 8000 
    hostname: "homework.otus"
    allowedRoutes:
      namespaces:
        from: Same

